//Usage_ID	Usage_Name
#define Unassigned                              0x00
#define Consumer_Control                        0x01
#define Numeric_Key_Pad                         0x02
#define Programmable_Buttons                    0x03
#define Microphone                              0x04
#define Headphone                               0x05
#define Graphic_Equalizer                       0x06
//07-1F	Reserved
#define Plus10                                  0x20
#define Plus100                                 0x21
#define AM_PM                                   0x22
//23-3F	Reserved
#define Power                                   0x30
#define Reset                                   0x31
#define Sleep                                   0x32
#define Sleep_After                             0x33
#define Sleep_Mode                              0x34
#define Illumination                            0x35
#define Function_Buttons                        0x36
//37-3F	Reserved
#define Menu                                    0x40
#define Menu_Pick                               0x41
#define Menu_Up                                 0x42
#define Menu_Down                               0x43
#define Menu_Left                               0x44
#define Menu_Right                              0x45
#define Menu_Escape                             0x46
#define Menu_Value_Increase                     0x47
#define Menu_Value_Decrease                     0x48
//49-5F	Reserved
#define Data_On_Screen                          0x60
#define Closed_Caption                          0x61
#define Closed_Caption_Select                   0x62
#define VCR_TV                                  0x63
#define Broadcast_Mode                          0x64
#define Snapshot                                0x65
#define Still                                   0x66
//67-7F	Reserved
#define Selection                               0x80
#define Assign_Selection                        0x81
#define Mode_Step                               0x82
#define Recall_Last                             0x83
#define Enter_Channel                           0x84
#define Order_Movie                             0x85
#define Channel                                 0x86
#define Media_Selection                         0x87
#define Media_Select_Computer                   0x88
#define Media_Select_TV                         0x89
#define Media_Select_WWW                        0x8A
#define Media_Select_DVD                        0x8B
#define Media_Select_Telephone                  0x8C
#define Media_Select_Program_Guide              0x8D
#define Media_Select_Video_Phone                0x8E
#define Media_Select_Games                      0x8F
#define Media_Select_Messages                   0x90
#define Media_Select_CD                         0x91
#define Media_Select_VCR                        0x92
#define Media_Select_Tuner                      0x93
#define Quit                                    0x94
#define Help                                    0x95
#define Media_Select_Tape                       0x96
#define Media_Select_Cable                      0x97
#define Media_Select_Satellite                  0x98
#define Media_Select_Security                   0x99
#define Media_Select_Home                       0x9A
#define Media_Select_Call                       0x9B
#define Channel_Increment                       0x9C
#define Channel_Decrement                       0x9D
#define Media_Select_SAP                        0x9E
//9F	Reserved
#define VCR_Plus                                0xA0
#define Once                                    0xA1
#define Daily                                   0xA2
#define Weekly                                  0xA3
#define Monthly                                 0xA4
//A5-AF	Reserved
#define Play                                    0xB0
#define Pause                                   0xB1
#define Record                                  0xB2
#define Fast_Forward                            0xB3
#define Rewind                                  0xB4
#define Scan_Next_Track                         0xB5
#define Scan_Previous_Track                     0xB6
#define Stop                                    0xB7
#define Eject                                   0xB8
#define Random_Play                             0xB9
#define Select_Disc                             0xBA
#define Enter_Disc                              0xBB
#define Repeat                                  0xBC
#define Tracking                                0xBD
#define Track_Normal                            0xBE
#define Slow_Tracking                           0xBF
#define Frame_Forward                           0xC0
#define Frame_Back                              0xC1
#define Mark                                    0xC2
#define Clear_Mark                              0xC3
#define Repeat_From_Mark                        0xC4
#define Return_To_Mark                          0xC5
#define Search_Mark_Forward                     0xC6
#define Search_Mark_Backwards                   0xC7
#define Counter_Reset                           0xC8
#define Show_Counter                            0xC9
#define Tracking_Increment                      0xCA
#define Tracking_Decrement                      0xCB
#define Stop_Eject                              0xCC
#define Play_Pause                              0xCD
#define Play_Skip                               0xCE
//CF-DF	Reserved
#define Volume                                  0xE0
#define Balance                                 0xE1
#define Mute                                    0xE2
#define Bass                                    0xE3
#define Treble                                  0xE4
#define Bass_Boost                              0xE5
#define Surround_Mode                           0xE6
#define Loudness                                0xE7
#define MPX                                     0xE8
#define Volume_Increment                        0xE9
#define Volume_Decrement                        0xEA
//EB-EF	Reserved
#define Speed_Select                            0xF0
#define Playback_Speed                          0xF1
#define Standard_Play                           0xF2
#define Long_Play                               0xF3
#define Extended_Play                           0xF4
#define Slow                                    0xF5
//F6-FF	Reserved
#define Fan_Enable                              0x100
#define Fan_Speed                               0x101
#define Light_Enable                            0x102
#define Light_Illumination_Level                0x103
#define Climate_Control_Enable                  0x104
#define Room_Temperature                        0x105
#define Security_Enable                         0x106
#define Fire_Alarm                              0x107
#define Police_Alarm                            0x108
#define Proximity                               0x109
#define Motion_O                                0x10A
#define Duress_Alarm_O                          0x10B
#define Holdup_Alarm_O                          0x10C
#define Medical_Alarm_O                         0x10D
//10E-14F	Reserved
#define Balance_Right                           0x150
#define Balance_Left                            0x151
#define Bass_Increment                          0x152
#define Bass_Decrement                          0x153
#define Treble_Increment                        0x154
#define Treble_Decrement                        0x155
//156-15F	Reserved
#define Speaker_System                          0x160
#define Channel_Left                            0x161
#define Channel_Right                           0x162
#define Channel_Center                          0x163
#define Channel_Front                           0x164
#define Channel_Center_Front                    0x165
#define Channel_Side                            0x166
#define Channel_Surround                        0x167
#define Channel_Low_Frequency_Enhancement       0x168
#define Channel_Top                             0x169
#define Channel_Unknown                         0x16A
//16B-16F	Reserved
#define Sub_channel                             0x170
#define Sub_channel_Increment                   0x171
#define Sub_channel_Decrement                   0x172
#define Alternate_Audio_Increment               0x173
#define Alternate_Audio_Decrement               0x174
//175-17F	Reserved
#define Application_Launch_Buttons              0x180
#define AL_Launch_Button_Configuration_Tool     0x181
#define AL_Programmable_Button_Configuration    0x182
#define AL_Consumer_Control_Configuration       0x183
#define AL_Word_Processor                       0x184
#define AL_Text_Editor                          0x185
#define AL_Spreadsheet                          0x186
#define AL_Graphics_Editor                      0x187
#define AL_Presentation_App                     0x188
#define AL_Database_App                         0x189
#define AL_Email_Reader                         0x18A
#define AL_Newsreader                           0x18B
#define AL_Voicemail                            0x18C
#define AL_Contacts_Address_Book                0x18D
#define AL_Calendar_Schedule                    0x18E
#define AL_Task_Project_Manager                 0x18F
#define AL_Log_Journal_Timecard                 0x190
#define AL_Checkbook_Finance                    0x191
#define AL_Calculator                           0x192
#define AL_AV_Capture_Playback                 0x193
#define AL_Local_Machine_Browser                0x194
#define AL_LAN_WAN_Browser                      0x195
#define AL_Internet_Browser                     0x196
#define AL_Remote_Networking_ISP_Connect        0x197
#define AL_Network_Conference                   0x198
#define AL_Network_Chat                         0x199
#define AL_Telephony_Dialer                     0x19A
#define AL_Logon                                0x19B
#define AL_Logoff                               0x19C
#define AL_Logon_Logoff                         0x19D
#define AL_Terminal_Lock_Screensaver            0x19E
#define AL_Control_Panel                        0x19F
#define AL_Command_Line_Processor_Run           0x1A0
#define AL_Process_Task_Manager                 0x1A1
#define AL_Select_Task_Application              0x1A2
#define AL_Next_Task_Application                0x1A3
#define AL_Previous_Task_Application            0x1A4
#define AL_Preemptive_Halt_Task_Application     0x1A5
#define AL_Integrated_Help_Center               0x1A6
#define AL_Documents                            0x1A7
#define AL_Thesaurus                            0x1A8
#define AL_Dictionary                           0x1A9
#define AL_Desktop                              0x1AA
#define AL_Spell_Check                          0x1AB
#define AL_Grammar_Check                        0x1AC
#define AL_Wireless_Status                      0x1AD
#define AL_Keyboard_Layout                      0x1AE
#define AL_Virus_Protection                     0x1AF
#define AL_Encryption                           0x1B0
#define AL_Screen_Saver                         0x1B1
#define AL_Alarms                               0x1B2
#define AL_Clock                                0x1B3
#define AL_File_Browser                         0x1B4
#define AL_Power_Status                         0x1B5
//1B6-1FF	Reserved
#define Generic_GUI_Application_Controls        0x200
#define AC_New                                  0x201
#define AC_Open                                 0x202
#define AC_Close                                0x203
#define AC_Exit                                 0x204
#define AC_Maximize                             0x205
#define AC_Minimize                             0x206
#define AC_Save                                 0x207
#define AC_Print                                0x208
#define AC_Properties                           0x209
#define AC_Undo                                 0x21A
#define AC_Copy                                 0x21B
#define AC_Cut                                  0x21C
#define AC_Paste                                0x21D
#define AC_Select_All                           0x21E
#define AC_Find                                 0x21F
#define AC_Find_and_Replace                     0x220
#define AC_Search                               0x221
#define AC_Go_To                                0x222
#define AC_Home                                 0x223
#define AC_Back                                 0x224
#define AC_Forward                              0x225
#define AC_Stop                                 0x226
#define AC_Refresh                              0x227
#define AC_Previous_Link                        0x228
#define AC_Next_Link                            0x229
#define AC_Bookmarks                            0x22A
#define AC_History                              0x22B
#define AC_Subscriptions                        0x22C
#define AC_Zoom_In                              0x22D
#define AC_Zoom_Out                             0x22E
#define AC_Zoom                                 0x22F
#define AC_Full_Screen_View                     0x230
#define AC_Normal_View                          0x231
#define AC_View_Toggle                          0x232
#define AC_Scroll_Up                            0x233
#define AC_Scroll_Down                          0x234
#define AC_Scroll                               0x235
#define AC_Pan_Left                             0x236
#define AC_Pan_Right                            0x237
#define AC_Pan                                  0x238
#define AC_New_Window                           0x239
#define AC_Tile_Horizontally                    0x23A
#define AC_Tile_Vertically                      0x23B
#define AC_Format                               0x23C
#define AC_Edit                                 0x23D
#define AC_Bold                                 0x23E
#define AC_Italics                              0x23F
#define AC_Underline                            0x240
#define AC_Strikethrough                        0x241
#define AC_Subscript                            0x242
#define AC_Superscript                          0x243
#define AC_All_Caps                             0x244
#define AC_Rotate                               0x245
#define AC_Resize                               0x246
#define AC_Flip_horizontal                      0x247
#define AC_Flip_Vertical                        0x248
#define AC_Mirror_Horizontal                    0x249
#define AC_Mirror_Vertical                      0x24A
#define AC_Font_Select                          0x24B
#define AC_Font_Color                           0x24C
#define AC_Font_Size                            0x24D
#define AC_Justify_Left                         0x24E
#define AC_Justify_Center_H                     0x24F
#define AC_Justify_Right                        0x250
#define AC_Justify_Block_H                      0x251
#define AC_Justify_Top                          0x252
#define AC_Justify_Center_V                     0x253
#define AC_Justify_Bottom                       0x254
#define AC_Justify_Block_V                      0x255
#define AC_Indent_Decrease                      0x256
#define AC_Indent_Increase                      0x257
#define AC_Numbered_List                        0x258
#define AC_Restart_Numbering                    0x259
#define AC_Bulleted_List                        0x25A
#define AC_Promote                              0x25B
#define AC_Demote                               0x25C
#define AC_Yes                                  0x25D
#define AC_No                                   0x25E
#define AC_Cancel                               0x25F
#define AC_Catalog                              0x260
#define AC_Buy_Checkout                         0x261
#define AC_Add_to_Cart                          0x262
#define AC_Expand                               0x263
#define AC_Expand_All                           0x264
#define AC_Collapse                             0x265
#define AC_Collapse_All                         0x266
#define AC_Print_Preview                        0x267
#define AC_Paste_Special                        0x268
#define AC_Insert_Mode                          0x269
#define AC_Delete                               0x26A
#define AC_Lock                                 0x26B
#define AC_Unlock                               0x26C
#define AC_Protect                              0x26D
#define AC_Unprotect                            0x26E
#define AC_Attach_Comment                       0x26F
#define AC_Delete_Comment                       0x270
#define AC_View_Comment                         0x271
#define AC_Select_Word                          0x272
#define AC_Select_Sentence                      0x273
#define AC_Select_Paragraph                     0x274
#define AC_Select_Column                        0x275
#define AC_Select_Row                           0x276
#define AC_Select_Table                         0x277
#define AC_Select_Object                        0x278
#define AC_Redo_Repeat                          0x279
#define AC_Sort                                 0x27A
#define AC_Sort_Ascending                       0x27B
#define AC_Sort_Descending                      0x27C
#define AC_Filter                               0x27D
#define AC_Set_Clock                            0x27E
#define AC_View_Clock                           0x27F
#define AC_Select_Time_Zone                     0x280
#define AC_Edit_Time_Zones                      0x281
#define AC_Set_Alarm                            0x282
#define AC_Clear_Alarm                          0x283
#define AC_Snooze_Alarm                         0x284
#define AC_Reset_Alarm                          0x285
#define AC_Synchronize                          0x286
#define AC_Send_Receive                         0x287
#define AC_Send_To                              0x288
#define AC_Reply                                0x289
#define AC_Reply_All                            0x28A
#define AC_Forward_Msg                          0x28B
#define AC_Send                                 0x28C
#define AC_Attach_File                          0x28D
#define AC_Upload                               0x28E
#define AC_Download                             0x28F
#define AC_Set_Borders                          0x290
#define AC_Insert_Row                           0x291
#define AC_Insert_Column                        0x292
#define AC_Insert_File                          0x293
#define AC_Insert_Picture                       0x294
#define AC_Insert_Object                        0x295
#define AC_Insert_Symbol                        0x296
#define AC_Save_and_Close                       0x297
#define AC_Rename                               0x298
#define AC_Merge                                0x299
#define AC_Split                                0x29A
#define AC_Disribute_Horizontally               0x29B
#define AC_Distribute_Vertically                0x29C
//29D-FFFF	Reserved